logo: /assets/headshot_pp.png
title: Michael Felix
description: I’m skilled in Data Science, Analytics, and Machine Learning, and I turn data into useful insights.
#show_downloads: true
theme: jekyll-theme-minimal
